esphome:
  name: esphome-web-1eeb60
  includes:
    - microphone_logger.h
  platformio_options:
    build_unflags:
      - '-D USE_AUDIO_NOISE_SUPPRESSION'

  friendly_name: ESPHome Web 1eeb60
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: "m3ex"
  password: "dragon775"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kolonkaesp32 Fallback Hotspot"
    password: "dogDJ0eNBG6O"

i2s_audio:
  i2s_lrclk_pin: GPIO26
  i2s_bclk_pin: GPIO18

microphone:
  - platform: i2s_audio
    i2s_din_pin: GPIO33
    id: adc_mic
    adc_type: external
    pdm: false

custom_component:
  - lambda: |-
      auto logger = new MicrophoneLogger(id(adc_mic));
      App.register_component(logger);

captive_portal:
